repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: prevent-credentials-commit
        name: Prevent credentials.json commit
        entry: |
          bash -c '
          if git diff --cached --name-only | grep -q "credentials.json"; then
            echo "Error: Attempting to commit credentials.json. Aborting."
            exit 1
          fi
          '
        language: system
        types: [file]

  - repo: local
    hooks:
      - id: prevent-private-key-commit
        name: Prevent private-key credentials.json commit
        entry: |
          bash -c '
          for file in $(git diff --cached --name-only); do
            # Skip .pre-commit-config.yaml and other excluded files
            if [[ "$file" == ".pre-commit-config.yaml" ]]; then
              continue
            fi
            # Check if the file contains "private_key"
            if [ -f "$file" ] && grep -q '"private_key"' "$file"; then
              echo "Error: Sensitive content detected in $file! Aborting commit."
              exit 1
            fi
          done
          '
        language: system
        types: [file]